### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by ciecus** [DeepGraphLearning/RecommenderSystems#1]
请问这些框架结构要求的数据格式是什么样的呢？

**Comment by Songweiping** [comment]
你好，
数据格式请参考各目录下的README文件。

**Comment by whiteyyc** [comment]
作者，您好：
        我目前在做动态网络表示学习，请问您可提供一下你实验数据吗？（论文里用的豆瓣原始数据就好，未被处理的，非常感谢，我的邮箱是1377281082@qq.com）
