### ISSUE TITLE
在SocialRec的test.py中batchsize被设为1

### ISSUE THREAD

**Issue by SSOTTY** [DeepGraphLearning/RecommenderSystems#15]
请问为什么您在训练集中将batchsize的值设为200，在测试集中却设置为1？
代码在test.py的第81行，内容为args.batch_size = 1。

**Comment by Songweiping** [comment]
测试集的batch size 设置为1是为了能够测试所有的测试样本，防止最后几个样本不能构成一个完整的batch size而无法测试。
