### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by DongZheng0030** [DeepGraphLearning/RecommenderSystems#2]
请问，Gowalla数据集是如何处理和划分的？

**Comment by Songweiping** [comment]
Gowalla数据的处理如下：
1. 过滤掉低频的user 和item。
2. 将每个user的历史信息按时间排序。
3. 取时间t，所有发生在t之前的check-ins作为训练数据，发生在t之后的check-ins作为评测数据。t的选取大致保证训练数据占80%。

我们提供的Gowalla数据只是为了说明sequential recommendation model的输入数据格式，谢谢！
