### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by whiteyyc** [DeepGraphLearning/RecommenderSystems#4]
作者，您好：
我目前在做动态网络表示学习，请问您可提供一下你实验数据吗？（论文里用的豆瓣原始数据就好，未被处理的，非常感谢，我的邮箱是1377281082@qq.com）

**Comment by Songweiping** [comment]
Hi,
Thanks for your interest in our work. The Douban data, which is released along with our WSDM'19 paper, is introduced [here](https://github.com/DeepGraphLearning/RecommenderSystems/blob/master/socialRec/README.md#douban-data). You can find the download url in that page. If you find the dataset useful in your work, please cite our WSDM'19 paper properly.
