### ISSUE TITLE
doubts about the data processing of Criteo in AutoInt

### ISSUE THREAD

**Issue by yfreedomliTHU** [DeepGraphLearning/RecommenderSystems#5]
@Songweiping ,Hello,I am very interested in your work(AutoInt) at CIKM'19,but I had some doubts when I reproduced the experiments of the paper.
As we know, Criteo has its own bench mark, including two csv files(train.csv & test.csv).But the preprocess of AutoInt splits the file(train_samples.txt) to get the train data,valid data and test data.
I'm wondering how to transform the original Dataset(train.csv & test.csv) into a Dataset that the data_process code can handle.
Could you post your code for converting original csv files(**train.csv & test.csv**) into the whole txt file(the data used in your paper, and Format is similar to the sample file **train_example.txt**)?

**Comment by Songweiping** [comment]
Sorry for the late reply.
IIRIC, we only used samples in train.csv for training/validation/testing. Under the featureRec/data/Dataprocess folder, we provide the codes for processing the four datasets used in our paper.
