### ISSUE TITLE
Converting to top-n recommendation

### ISSUE THREAD

**Issue by joohyelim** [DeepGraphLearning/RecommenderSystems#6]
I am very impressed about the usefulness of AutoInt to my personal project. 
I'm wondering if there is any handy way of converting this AutoInt to top-n recommendaiton? 
Would it be possible?

**Comment by Songweiping** [comment]
I think you can first pair the target user with all possible items and then score each <TargetUser, item> pair with AutoInt model. To get top-n recommendations, just rank all candidate items based on predicted scores.
