### ISSUE TITLE
Only One class present issue 

### ISSUE THREAD

**Issue by joohyelim** [DeepGraphLearning/RecommenderSystems#7]
I am working on my own data -purchase history of financial production. 
So I have data as who, with features, purchased which products, with features and when. 
However, I have found that the metric of the model is AUC -- and I, as expected, get the following error 

**ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.**

Since all my Ys are 1s -as I only have who purchased (clicked) which and there is no 0 value ( who didn't purchase which). 
As other CTR prediction models also use AUC and log loss, I assume that there must be a way to use AUC for such a dataset. 

Do you have any idea how to solve this issue? 
That would be really helpful!

**Comment by Songweiping** [comment]
For any classification problem, we need more than one class. In your case, IIUIC, the collected data only contains positive examples, i.e., clicks. To evaluate the model, you need to construct negative samples by combining a user with some items that he/she didn't click, forming zero Ys.
