### ISSUE TITLE
 Extracting Attention And Visualize it 

### ISSUE THREAD

**Issue by joohyelim** [DeepGraphLearning/RecommenderSystems#8]
![weight](https://user-images.githubusercontent.com/22454303/76831884-875c8b80-686b-11ea-9403-27be5906ba29.PNG)

After running the model, I am wondering if weights of attention and their visualization can be done as the attached file displays from the original paper. 

There are many examples for extracting and visualization for seq2seq but couldn't really find one for feature explanation. 

Is there any ideas/code that can be used for attention visualization of meaningful features? ?

**Comment by Songweiping** [comment]
We extract attention weight from this [line](https://github.com/DeepGraphLearning/RecommenderSystems/blob/0a585139de1b49d72511ce5a4a642bd427c1349a/featureRec/autoint/model.py#L79). For visualization, we just use Python Matpoltlib.
