### ISSUE TITLE
UniformNeighborSampler in SocialRec

### ISSUE THREAD

**Issue by lamnvs** [DeepGraphLearning/RecommenderSystems#9]
While I was looking through the code, I noticed that in neigh_samplers.py, users can sample themselves as the second-order neighbors because when we sample 10 neighbors of the first-order neighbor, the user is also included.

            adj = self.adj_info[node, :]
            neighbors = []
            for neighbor in adj:
                if first_or_second == 'second':
                    if self.visible_time[neighbor] <= timeid:
                        neighbors.append(neighbor)    
I was wondering is this intended or a logic flaw. Thank you!

**Comment by Songweiping** [comment]
This is intended and I think it's a common practice in message passing-based models. You may  check figure 1 in https://arxiv.org/pdf/1806.01973.pdf for a better understanding.

**Comment by lamnvs** [comment]
Thank you very much!
